# Generated by Django 4.1.1 on 2022-09-29 13:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("jobportal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
