# Generated by Django 4.1.1 on 2022-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobportal", "0002_alter_applicant_email_alter_applicant_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNREVIEWED", "UNREVIEWED"),
                    ("SELECTED", "SELECTED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="UNREVIEWED",
                max_length=32,
            ),
        ),
    ]
